name: My workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_FORCE_RUBY_PLATFORM: true
      BUNDLE_BUILD__NOKOGIRI: --use-system-libraries
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: |
            build-essential
            ruby-dev
            zlib1g-dev
            liblzma-dev
            patch
            libxml2-dev
            libxslt-dev
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rake
      - run: ls -l
      - run: cat index.fo
